AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  scheduling_assessment

  Sample SAM Template for scheduling_assessment

# More info about Globals: https://github.com/awslabs/serverless-application-model/blob/master/docs/globals.rst
Globals:
  Function:
    CodeUri: target/scheduling_assessment-0.0.1-SNAPSHOT.jar
    Timeout: 20
    Runtime: java11
    Handler: org.springframework.cloud.function.adapter.aws.FunctionInvoker::handleRequest

Resources:
  ChapterCalendarFunction:
    Type: AWS::Serverless::Function # More info about Function Resource: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#awsserverlessfunction
    Properties:
      MemorySize: 1024
      Environment: # More info about Env Vars: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#environment-object
        Variables:
          SPRING_CLOUD_FUNCTION_DEFINITION: ChapterCalendarHandler
          JAVA_TOOL_OPTIONS: -XX:+TieredCompilation -XX:TieredStopAtLevel=1 # More info about tiered compilation https://aws.amazon.com/blogs/compute/optimizing-aws-lambda-function-performance-for-java/
      Events:
        ScheduleEvent:
          Type: Api # More info about API Event Source: https://github.com/awslabs/serverless-application-model/blob/master/versions/2016-10-31.md#api
          Properties:
            Path: /scheduleEvent
            Method: POST

Outputs:
  ApiEndpoint:
    Description: "API Gateway endpoint URL for Dev stage for Chapter Calendar function"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Dev/scheduleEvent/"
